### ISSUE TITLE
Enable OAuth restriction on the usacs organization

### ISSUE THREAD

**Issue by bilalq** [usacs/usacs.github.io#150]
Hello, friends!

I'm an old alumnus from 2013. I don't know if the current generation actually still uses this Github organization account, but it's really awesome to see how much things have taken off since we first started USACS and HackRU back in the day. Big respect to everyone. 

That aside, this org currently has its OAuth permissions left very open. When third party apps request permissions, there's no way to exclude the [usacs](https://github.com/usacs) org and its repos from there, making it pretty annoying.

Owners/admins of this org should be able to enable access restrictions at this URL:
https://github.com/organizations/usacs/settings/oauth_application_policy

Related docs can be found here:
https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/about-oauth-app-access-restrictions

I don't have a good way of contacting the current USACS group, so I'm just gonna @ mention the first 5 people listed as owners for now.

@agoodkind 
@alimohamad 
@amulya 
@benplus1 
@davidchen

**Comment by davidchen** [comment]
Good catch Bilal, I've enabled access restrictions for now. If current USACS members have any issues with restrictions, I'd advise having an internal discussion as to why that would be as I'm no longer at the university. Have a good one guys!
