### ISSUE TITLE
mission statement is in a tiny centered column

### ISSUE THREAD

**Issue by mjrb** [usacs/usacs.github.io#64]

**Comment by hemangandhi** [comment]
OK... let me know what you have in mind for this... I couldn't think of a much better way to present all of it. I'm down for sections (like a folding accordion) or something.

**Comment by mjrb** [comment]
I was kind of thinking of maybe putting in a centered container, aligning left and maybe making the font a bit bigger. Increasing the font would help it take up space on the page but it would probably look inconsistent and weird.

**Comment by hemangandhi** [comment]
Thanks for the fix!
