### ISSUE TITLE
for many pages the background cuts out before the end of the page

### ISSUE THREAD

**Issue by mjrb** [usacs/usacs.github.io#65]
for example look at how the PCB looking background cuts out on this page
http://usacs.rutgers.edu/contact.html

**Comment by three** [comment]
This is happening because the height of `#content` does not take up the full page. I'm not sure why or what's causing it but this can be fixed with `#content { height: 100% }`.

**Comment by mjrb** [comment]
thanks, @three i pushed this to my fork
