### ISSUE TITLE
the footer renders weird on pages that dont scroll

### ISSUE THREAD

**Issue by mjrb** [usacs/usacs.github.io#80]
atleast on firefox 56
it's most likely because of the footer being at the bottom of the page so it renders it in spot
theres probably some bootstrap class to fix this

**Comment by hemangandhi** [comment]
Sure. I see what you mean.

**Comment by mjrb** [comment]
http://usacs.rutgers.edu/get-involved.html
vs
http://usacs.rutgers.edu/events.html

**Comment by hemangandhi** [comment]
Screenshots please? (My firefox isn't behaving the same way.)

Also, before the full pages loads, I don't care too much right now... is it a width issue? We could make the footer fade out on the sides too.

**Comment by mjrb** [comment]
![screenshot from 2017-11-01 00-03-03](https://user-images.githubusercontent.com/314083/32259626-22725db4-be98-11e7-823d-6f56276ccd0c.png)
![screenshot from 2017-11-01 00-02-54](https://user-images.githubusercontent.com/314083/32259631-2716c558-be98-11e7-8276-3b16aef74e99.png)

**Comment by hemangandhi** [comment]
Ah... yeah, IDK the CSS. I'll figure it out unless you beat me to it. I think I can replicate this by zooming out.

**Comment by mjrb** [comment]
waitup on pushing it, im re factor the website for templates and its a pain in to reconcile all these comits

**Comment by hemangandhi** [comment]
OK. Yeah, let's revisit once templates are done.
